# 配置多数据源
spring:
  datasource:
    hikari:
      # 配置第一个数据源
      d1:
        jdbc-url: jdbc:mysql://xx.xx.xx.xx:xxxx/d1?useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
        username: xxxxxx
        password: xxxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver
      # 配置第二个数据源
      d2:
        jdbc-url: jdbc:mysql://xx.xx.xx.xx:xxxx/d2?useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
        username: xxxxxx
        password: xxxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver